version: '3.11'

services:
  vuln-manager-web:
    container_name: vuln-manager-web
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/static
    ports:
      - "8000:8000"
    environment:
      - DEBUG=${DEBUG:-1}
      - DJANGO_SETTINGS_MODULE=config.settings
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
    depends_on:
      - db

  db:
    container_name: vuln-manager-db
    image: postgres:15
    volumes:
      - vuln_manager_postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}

volumes:
  vuln_manager_postgres_data:
    name: vuln_manager_postgres_data
  static_volume:
    name: vuln_manager_static_volume 