# Generated by Django 4.2.10 on 2025-06-11 00:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('hardware', 'Hardware'), ('software', 'Software'), ('servicio', 'Servicio'), ('red', 'Dispositivo de Red'), ('otro', 'Otro')], max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('palabras_clave', models.TextField(help_text='Palabras clave separadas por comas para búsqueda de CVEs')),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('puerto', models.IntegerField(blank=True, null=True)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Activo',
                'verbose_name_plural': 'Activos',
            },
        ),
        migrations.CreateModel(
            name='ActivoVulnerabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('resuelta', 'Resuelta'), ('falso_positivo', 'Falso Positivo')], default='pendiente', max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('fecha_deteccion', models.DateField(auto_now_add=True)),
                ('fecha_resolucion', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vuln_manager.activo')),
            ],
            options={
                'verbose_name': 'Vulnerabilidad de Activo',
                'verbose_name_plural': 'Vulnerabilidades de Activos',
            },
        ),
        migrations.CreateModel(
            name='Vulnerabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_id', models.CharField(max_length=20, unique=True)),
                ('descripcion_en', models.TextField(verbose_name='Descripción (Inglés)')),
                ('descripcion_es', models.TextField(verbose_name='Descripción (Español)')),
                ('severidad', models.CharField(choices=[('critica', 'Crítica'), ('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], max_length=20)),
                ('status', models.CharField(choices=[('published', 'Publicado'), ('rejected', 'Rechazado'), ('draft', 'Borrador')], default='published', max_length=20)),
                ('fecha_publicacion', models.DateField()),
                ('fecha_modificacion', models.DateField()),
                ('fecha_deteccion', models.DateField(auto_now_add=True)),
                ('cvss2_score', models.FloatField(blank=True, null=True, verbose_name='Score CVSS v2')),
                ('cvss2_severidad', models.CharField(blank=True, max_length=20, null=True, verbose_name='Severidad CVSS v2')),
                ('cvss2_vector', models.CharField(blank=True, max_length=100, null=True, verbose_name='Vector CVSS v2')),
                ('cvss3_score', models.FloatField(blank=True, null=True, verbose_name='Score CVSS v3')),
                ('cvss3_severidad', models.CharField(blank=True, max_length=20, null=True, verbose_name='Severidad CVSS v3')),
                ('cvss3_vector', models.CharField(blank=True, max_length=100, null=True, verbose_name='Vector CVSS v3')),
                ('referencias', models.JSONField(blank=True, default=list, verbose_name='URLs de Referencia')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activos', models.ManyToManyField(through='vuln_manager.ActivoVulnerabilidad', to='vuln_manager.activo')),
            ],
            options={
                'verbose_name': 'Vulnerabilidad',
                'verbose_name_plural': 'Vulnerabilidades',
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('cve', 'Actualización de CVEs'), ('scan', 'Escaneo de Activos')], max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('programacion', models.CharField(help_text="Expresión cron (ej: '0 0 * * *' para diario a medianoche)", max_length=100)),
                ('ultima_ejecucion', models.DateTimeField(blank=True, null=True)),
                ('proxima_ejecucion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('programada', 'Programada'), ('ejecutando', 'Ejecutando'), ('completada', 'Completada'), ('error', 'Error'), ('cancelada', 'Cancelada')], default='programada', max_length=20)),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tarea Programada',
                'verbose_name_plural': 'Tareas Programadas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EjecucionTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('exitoso', 'Exitoso'), ('error', 'Error'), ('cancelado', 'Cancelado')], max_length=20)),
                ('resultado', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('ejecutada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejecuciones', to='vuln_manager.tarea')),
            ],
            options={
                'verbose_name': 'Ejecución de Tarea',
                'verbose_name_plural': 'Ejecuciones de Tareas',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analistas', models.ManyToManyField(related_name='clientes_gestionados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('nueva', 'Nueva'), ('vista', 'Vista'), ('en_proceso', 'En Proceso'), ('resuelta', 'Resuelta'), ('ignorada', 'Ignorada')], default='nueva', max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vuln_manager.activo')),
                ('analista_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('resuelta_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_resueltas', to=settings.AUTH_USER_MODEL)),
                ('vulnerabilidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vuln_manager.vulnerabilidad')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='activovulnerabilidad',
            name='vulnerabilidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vuln_manager.vulnerabilidad'),
        ),
        migrations.AddField(
            model_name='activo',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activos', to='vuln_manager.cliente'),
        ),
        migrations.AlterUniqueTogether(
            name='activovulnerabilidad',
            unique_together={('activo', 'vulnerabilidad')},
        ),
    ]
