# Generated by Django 4.2.10 on 2025-06-11 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuln_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vulnerabilidad',
            name='cvss3_severidad',
            field=models.CharField(blank=True, choices=[('critica', 'Crítica'), ('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], max_length=20, null=True, verbose_name='Severidad CVSS v3'),
        ),
    ]
