# Generated by Django 4.2.10 on 2025-06-13 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vuln_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activovulnerabilidad',
            name='activo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relaciones_vulnerabilidad', to='vuln_manager.activo'),
        ),
    ]
