# Generated by Django 4.2.10 on 2025-06-13 00:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vuln_manager', '0002_alter_activovulnerabilidad_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='activovulnerabilidad',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='activovulnerabilidad',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
