# Generated by Django 4.2.10 on 2025-06-13 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuln_manager', '0003_activovulnerabilidad_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vulnerabilidad',
            name='cvss2_score',
        ),
        migrations.RemoveField(
            model_name='vulnerabilidad',
            name='cvss2_severidad',
        ),
        migrations.RemoveField(
            model_name='vulnerabilidad',
            name='cvss2_vector',
        ),
        migrations.AddField(
            model_name='vulnerabilidad',
            name='cvss4_score',
            field=models.FloatField(blank=True, null=True, verbose_name='Score CVSS v4'),
        ),
        migrations.AddField(
            model_name='vulnerabilidad',
            name='cvss4_severidad',
            field=models.CharField(blank=True, choices=[('critica', 'Crítica'), ('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], max_length=20, null=True, verbose_name='Severidad CVSS v4'),
        ),
        migrations.AddField(
            model_name='vulnerabilidad',
            name='cvss4_vector',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Vector CVSS v4'),
        ),
    ]
