# Generated by Django 4.2.10 on 2025-06-13 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuln_manager', '0004_remove_vulnerabilidad_cvss2_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vulnerabilidad',
            name='cvss3_vector',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Vector CVSS v3'),
        ),
        migrations.AlterField(
            model_name='vulnerabilidad',
            name='cvss4_vector',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Vector CVSS v4'),
        ),
    ]
