# Generated by Django 4.2.10 on 2025-06-13 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuln_manager', '0005_alter_vulnerabilidad_cvss3_vector_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vulnerabilidad',
            name='cvss3_score',
        ),
        migrations.RemoveField(
            model_name='vulnerabilidad',
            name='cvss3_severidad',
        ),
        migrations.RemoveField(
            model_name='vulnerabilidad',
            name='cvss3_vector',
        ),
        migrations.RemoveField(
            model_name='vulnerabilidad',
            name='cvss4_score',
        ),
        migrations.RemoveField(
            model_name='vulnerabilidad',
            name='cvss4_severidad',
        ),
        migrations.RemoveField(
            model_name='vulnerabilidad',
            name='cvss4_vector',
        ),
        migrations.AddField(
            model_name='vulnerabilidad',
            name='cvss_data',
            field=models.JSONField(blank=True, default=dict, help_text="Datos de CVSS en formato: {'v3.0': {'score': 6.7, 'severidad': 'MEDIUM', 'vector': '...'}}", verbose_name='Datos CVSS'),
        ),
        migrations.AlterField(
            model_name='vulnerabilidad',
            name='severidad',
            field=models.CharField(choices=[('critical', 'Crítica'), ('high', 'Alta'), ('medium', 'Media'), ('low', 'Baja'), ('no_establecida', 'No Establecida')], max_length=20),
        ),
    ]
