# Generated by Django 4.2.10 on 2025-06-14 23:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vuln_manager', '0006_remove_vulnerabilidad_cvss3_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejecuciontarea',
            name='cves_actualizadas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ejecuciontarea',
            name='cves_nuevas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ejecuciontarea',
            name='cves_procesadas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ejecuciontarea',
            name='cves_rechazadas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tarea',
            name='dias_atras',
            field=models.PositiveIntegerField(default=1, help_text='Número de días hacia atrás para buscar CVEs'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='incluir_rechazadas',
            field=models.BooleanField(default=False, help_text='Incluir CVEs rechazadas en la búsqueda'),
        ),
        migrations.AlterField(
            model_name='ejecuciontarea',
            name='ejecutada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ejecuciones_tarea', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='creada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='programacion',
            field=models.CharField(help_text="Expresión cron (ej: '0 0 * * *' para diario a medianoche)", max_length=100, validators=[django.core.validators.RegexValidator(message='Formato de expresión cron inválido', regex='^(\\*|[0-9]{1,2}|\\*\\/[0-9]{1,2})(\\s+(\\*|[0-9]{1,2}|\\*\\/[0-9]{1,2})){4}$')]),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='tipo',
            field=models.CharField(choices=[('cve', 'Actualización de CVEs')], max_length=20),
        ),
    ]
