# Generated by Django 4.2.10 on 2025-06-15 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vuln_manager', '0007_ejecuciontarea_cves_actualizadas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='incluir_rechazadas',
        ),
    ]
