# Generated by Django 4.2.10 on 2025-06-15 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vuln_manager', '0008_remove_tarea_incluir_rechazadas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ejecuciontarea',
            name='cves_rechazadas',
        ),
    ]
