# Generated by Django 4.2.10 on 2025-06-15 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vuln_manager', '0011_modify_tarea_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='usuario',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='analistacliente',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relaciones_analista_cliente', to='vuln_manager.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='estado',
            field=models.CharField(choices=[('programada', 'Programada'), ('pausada', 'Pausada')], default='programada', help_text='Estado general de la tarea: programada o pausada', max_length=20),
        ),
    ]
