# Generated by Django 4.2.10 on 2025-06-16 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vuln_manager', '0012_cliente_usuario_alter_analistacliente_cliente_and_more'),
        ('vuln_manager', '0012_ensure_cve_collector'),
    ]

    operations = [
    ]
