# Generated by Django 4.2.10 on 2025-06-16 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuln_manager', '0013_merge_20250616_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vulnerabilidad',
            name='severidad',
            field=models.CharField(choices=[('critica', 'Crítica'), ('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja'), ('no establecida', 'No Establecida')], max_length=20),
        ),
    ]
