# Generated by Django 4.2.10 on 2025-06-16 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuln_manager', '0016_alter_cliente_options_alter_cliente_analistas_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['username'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AddField(
            model_name='vulnerabilidad',
            name='cvss_score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Score CVSS'),
        ),
        migrations.AddField(
            model_name='vulnerabilidad',
            name='cvss_severidad',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Severidad CVSS'),
        ),
        migrations.AlterField(
            model_name='vulnerabilidad',
            name='cvss_data',
            field=models.JSONField(blank=True, default=dict, help_text='Datos de CVSS en formato original de la API', verbose_name='Datos CVSS'),
        ),
    ]
